### PR TITLE
Update traefik.yml

### PR DESCRIPTION
**Pull request by contactnat**
By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.

### CODE REVIEW

**Comment by timothystewart6** [comment]
Curious if we should add a comment to this, or comment it out by default?

**Comment by contactnat** [comment]
> Curious if we should add a comment to this, or comment it out by default?

I thought about this too, I think commenting it out by default is the right approach, being that it seems to be specific to cloudlfare.

**Comment by timothystewart6** [comment]
Thanks!  How about commenting it out then and adding a comment to it and I will merge it!

**Comment by contactnat** [comment]
> Thanks! How about commenting it out then and adding a comment to it and I will merge it!

oops, github virgin here, its collaborative so yep I could have made that change.. anyway - done, not sure about you but the comment looks to long to me.

**Comment by timothystewart6** [comment]
All good!  Thank you so much!  Merging and new site rolling out!

**Pull request merged**
