### PR TITLE
Update to rancher in docker page

### PR DESCRIPTION
**Pull request by ChrisThePCGeek**
Kazuto and I determined you need to run the docker run command as root or with sudo in order to use the --privileged flag

### CODE REVIEW

**Comment by timothystewart6** [comment]
Hmmm.  Not sure this is needed if you added the user to the sodoers and you use that use to spin this up.   If this is the case, this seems like a bug with docker.

**Comment by ChrisThePCGeek** [comment]
It resolved the issue of the error logs saying privileged is required for
the person I was talking to in containerization last night.  And they had
added their user to the docker group.  I had tried to reinstall mine on
Ubuntu a couple weeks ago and it kept crashing too, I didn't see why but I
too had done it as myself and not as root or with sudo.

**Comment by timothystewart6** [comment]
I just tested this on my single node rancher system and could not reproduce:

* Rancher was `2.5.1` started with the `--privileged` flag
* upgraded to `2.5.9`
* updated Ubuntu `20.04` with all patches
* this updated docker to `20.10.8`
* then, I even updated kubernetes within Rancher from `1.19.4` to `1.20.9`


```
0c9ff7608dd   rancher/rancher:latest                                     "entrypoint.sh"          15 minutes ago       Up 7 minutes        0.0.0.0:9090->80/tcp, :::9090->80/tcp, 0.0.0.0:9091->443/tcp, :::9091->443/tcp   rancher_docker_server
```
I am not saying that the supplied fix you are suggesting didn't fix his issue, just stating what I am seeing and that this seems like an edge case.

I'd feel more comfortable just adding this to the troubleshooting steps, mentioning that you may need to run docker with `sudo` even if they are in the `sudoers` group due to a bug in some version of rancher rather than updating the primary command. 

If you don't want to change this PR, I can create one to update the docs.  If you do update the PR, can you squash and remove unrelated commits?  It seems like there are commits to change other pages not in the PR.

Thank you!

**Comment by timothystewart6** [comment]
closing since this seems to be an issue upstream with rancher and `sudo` doesn't actually fix this.  Thank you though!

**Pull request closed without merging**
